#!/usr/bin/env python3
"""Applies the app's manually curated small-place rows to an existing places.db asset."""

import sqlite3
import sys


MANUAL_PLACES = [
    (-1000001, "Qomhane", "قمحانة", "Qomhane", "SY", 35.195792, 36.732304, "Asia/Damascus", 0),
]

# Generated by Room for PlacesDatabase v2. A pre-packaged database must carry the exact
# identity hash expected by the current entity schema, including its declared indexes.
ROOM_IDENTITY_HASH_V2 = "63e97657ef1e0ae68d3e6db459e817f6"


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("Usage: apply_manual_places.py <places.db>")

    connection = sqlite3.connect(sys.argv[1])
    try:
        connection.executemany(
            """
            INSERT OR REPLACE INTO places
                (geonameId, nameEn, nameAr, asciiName, countryCode, latitude, longitude, timeZoneId, population)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            MANUAL_PLACES,
        )
        connection.execute("INSERT INTO places_fts(places_fts) VALUES('rebuild')")
        connection.execute(
            "INSERT OR REPLACE INTO room_master_table (id, identity_hash) VALUES (42, ?)",
            (ROOM_IDENTITY_HASH_V2,),
        )
        connection.execute("PRAGMA user_version=2")
        connection.commit()
    finally:
        connection.close()


if __name__ == "__main__":
    main()
