package com.prayertimes.data.places

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

/**
 * Confirms the bundled app/src/main/assets/places.db (generated by
 * tools/geonames/build_places_db.py) actually opens via Room's createFromAsset with the schema
 * PlaceEntity/PlacesDatabase expect, and contains real, sane GeoNames data.
 */
@RunWith(RobolectricTestRunner::class)
class PlacesAssetTest {

    private val madinahLat = 24.4672
    private val madinahLon = 39.6111

    @Test
    fun `bundled asset opens and resolves Madinah near its known coordinates`() = runTest {
        val context = ApplicationProvider.getApplicationContext<Context>()
        val db = Room.databaseBuilder(context, PlacesDatabase::class.java, "places_asset_test.db")
            .createFromAsset("places.db")
            .build()

        val candidates = db.placeDao().candidatesInBoundingBox(
            madinahLat - 0.5, madinahLat + 0.5, madinahLon - 0.5, madinahLon + 0.5
        )
        assertTrue("expected candidates near Madinah", candidates.isNotEmpty())
        assertTrue(candidates.any { it.nameEn == "Madinah" && it.nameAr == "المدينة المنورة" })

        val cairoSearch = db.placeDao().search(PlaceRepository.buildSearchQuery("cairo")!!)
        assertTrue(cairoSearch.any { it.nameAr == "القاهرة" })

        val englishSearchWhileArabicCanDisplay = db.placeDao().search(PlaceRepository.buildSearchQuery("madinah")!!)
        assertTrue(englishSearchWhileArabicCanDisplay.any { it.nameAr == "المدينة المنورة" })

        db.close()
    }
}
